parameters:
#    usuario.example.class: Prode2014\UsuarioBundle\Example

services:
    login_listener:
        class: Prode\UsuarioBundle\Listener\LoginListener
        arguments: [@security.context, @router, @doctrine]
        tags:
             - { name: kernel.event_listener, event: security.interactive_login }
             - { name: kernel.event_listener, event: kernel.response }